export default {
  data: {
    TournID: 66098,
    ResultID: 210008760,
    FirstName: "Gannon",
    LastName: "Buhr",
    PDGANum: 75412,
    Division: "MPO",
    Pool: "",
    Place: 1,
    PlaceRank: 2,
    ToPar: -20,
    Tied: false,
    Prize: "",
    DNF: false,
    Total: 116,
    Name: "Gannon Buhr",
    Avatar: "/files/styles/large/public/pictures/Gannon-Buhr.jpg",
    ProfileURL: "https://www.pdga.com/player/75412",
    DivisionName: "Mixed Pro Open",
    FormattedPlace: "1st",
    TierLetter: "A",
    TierType: "Tier",
    Class: "Professional",
    Rating: 1043,
    RatingEffectiveDate: "2023-06-13",
    Location: "Urbandale, IA",
    Country: "US",
    Nationality: null,
    Privacy: "no",
    AvatarURL: "/files/styles/large/public/pictures/Gannon-Buhr.jpg",
    Scores: [
      {
        Round: 1,
        RoundLabel: "Round 1",
        RoundLabelShort: "Rd 1",
        RoundDate: "2023-07-09",
        RoundField: "Rd1",
        TeeTime: "15:25:00",
        TeeStart: "1",
        RoundScore: 60,
        ScoreToPar: -8,
        RoundToPar: -8,
        Birdies: 11,
        BirdieHoles: 11,
        Bogeys: 3,
        BogeyHoles: 3,
        HotRound: false,
        RoundComplete: true,
        RoundRating: 1051,
        HoleScores: {
          1: 3,
          2: 3,
          3: 5,
          4: 3,
          5: 3,
          6: 4,
          7: 3,
          8: 4,
          9: 2,
          10: 4,
          11: 4,
          12: 4,
          13: 2,
          14: 3,
          15: 2,
          16: 4,
          17: 3,
          18: 4,
        },
        Layout: {
          CourseName: "Bad Rock Creek Disc Golf Course",
          ShortCourseName: "Bad Rock Creek",
          Name: "MPO @ BRC",
          ShortName: "MPO @ BRC",
          Holes: 18,
          Par: 68,
          Length: 10092,
          Units: "Feet",
          Detail: {
            1: {
              Label: "1",
              Length: 575,
              Par: 4,
            },
            10: {
              Label: "10",
              Length: 487,
              Par: 3,
            },
            11: {
              Label: "11",
              Length: 383,
              Par: 3,
            },
            12: {
              Label: "12",
              Length: 652,
              Par: 5,
            },
            13: {
              Label: "13",
              Length: 364,
              Par: 3,
            },
            14: {
              Label: "14",
              Length: 711,
              Par: 4,
            },
            15: {
              Label: "15",
              Length: 288,
              Par: 3,
            },
            16: {
              Label: "16",
              Length: 956,
              Par: 5,
            },
            17: {
              Label: "17",
              Length: 461,
              Par: 4,
            },
            18: {
              Label: "18",
              Length: 924,
              Par: 5,
            },
            2: {
              Label: "2",
              Length: 204,
              Par: 3,
            },
            3: {
              Label: "3",
              Length: 605,
              Par: 4,
            },
            4: {
              Label: "4",
              Length: 835,
              Par: 4,
            },
            5: {
              Label: "5",
              Length: 624,
              Par: 4,
            },
            6: {
              Label: "6",
              Length: 588,
              Par: 4,
            },
            7: {
              Label: "7",
              Length: 411,
              Par: 3,
            },
            8: {
              Label: "8",
              Length: 756,
              Par: 4,
            },
            9: {
              Label: "9",
              Length: 268,
              Par: 3,
            },
          },
        },
      },
      {
        Round: 2,
        RoundLabel: "Round 2",
        RoundLabelShort: "Rd 2",
        RoundDate: "2023-07-09",
        RoundField: "Rd2",
        TeeTime: "15:25:00",
        TeeStart: "1",
        RoundScore: 56,
        ScoreToPar: -12,
        RoundToPar: -12,
        Birdies: 12,
        BirdieHoles: 12,
        Bogeys: 0,
        BogeyHoles: 0,
        HotRound: false,
        RoundComplete: true,
        RoundRating: 1074,
        HoleScores: {
          1: 3,
          2: 2,
          3: 4,
          4: 4,
          5: 4,
          6: 3,
          7: 2,
          8: 4,
          9: 2,
          10: 3,
          11: 2,
          12: 4,
          13: 2,
          14: 3,
          15: 3,
          16: 4,
          17: 3,
          18: 4,
        },
        Layout: {
          CourseName: "Bad Rock Creek Disc Golf Course",
          ShortCourseName: "Bad Rock Creek",
          Name: "MPO @ BRC",
          ShortName: "MPO @ BRC",
          Holes: 18,
          Par: 68,
          Length: 10092,
          Units: "Feet",
          Detail: {
            1: {
              Label: "1",
              Length: 575,
              Par: 4,
            },
            10: {
              Label: "10",
              Length: 487,
              Par: 3,
            },
            11: {
              Label: "11",
              Length: 383,
              Par: 3,
            },
            12: {
              Label: "12",
              Length: 652,
              Par: 5,
            },
            13: {
              Label: "13",
              Length: 364,
              Par: 3,
            },
            14: {
              Label: "14",
              Length: 711,
              Par: 4,
            },
            15: {
              Label: "15",
              Length: 288,
              Par: 3,
            },
            16: {
              Label: "16",
              Length: 956,
              Par: 5,
            },
            17: {
              Label: "17",
              Length: 461,
              Par: 4,
            },
            18: {
              Label: "18",
              Length: 924,
              Par: 5,
            },
            2: {
              Label: "2",
              Length: 204,
              Par: 3,
            },
            3: {
              Label: "3",
              Length: 605,
              Par: 4,
            },
            4: {
              Label: "4",
              Length: 835,
              Par: 4,
            },
            5: {
              Label: "5",
              Length: 624,
              Par: 4,
            },
            6: {
              Label: "6",
              Length: 588,
              Par: 4,
            },
            7: {
              Label: "7",
              Length: 411,
              Par: 3,
            },
            8: {
              Label: "8",
              Length: 756,
              Par: 4,
            },
            9: {
              Label: "9",
              Length: 268,
              Par: 3,
            },
          },
        },
      },
    ],
    AverageRoundRating: 1063,
    RatingDiff: 20,
    ToParString: -20,
    Teammates: [],
  },
  hash: "ddd2012940eefc3eb7094f2674aa2d3f",
};
