export default {
  data: {
    TournID: 66098,
    ResultID: 210008830,
    FirstName: "Joseph",
    LastName: "Anderson",
    PDGANum: 122356,
    Division: "MPO",
    Pool: "",
    Place: 1,
    PlaceRank: 1,
    ToPar: -13,
    Tied: false,
    Prize: "",
    DNF: false,
    Total: 55,
    Name: "Joseph Anderson",
    Avatar:
      "/files/styles/large/public/pictures/picture-1648431-1606604275.jpg",
    ProfileURL: "https://www.pdga.com/player/122356",
    DivisionName: "Mixed Pro Open",
    FormattedPlace: "1st",
    TierLetter: "A",
    TierType: "Tier",
    Class: "Professional",
    Rating: 1027,
    RatingEffectiveDate: "2023-06-13",
    Location: "Athens, GA",
    Country: "US",
    Nationality: null,
    Privacy: "no",
    AvatarURL:
      "/files/styles/large/public/pictures/picture-1648431-1606604275.jpg",
    Scores: [
      {
        Round: 1,
        RoundLabel: "Round 1",
        RoundLabelShort: "Rd 1",
        RoundDate: "2023-07-09",
        RoundField: "Rd1",
        TeeTime: "13:20:00",
        TeeStart: "1",
        RoundScore: 55,
        ScoreToPar: -13,
        RoundToPar: -13,
        Birdies: 13,
        BirdieHoles: 12,
        Bogeys: 0,
        BogeyHoles: 0,
        HotRound: false,
        RoundComplete: true,
        RoundRating: 1081,
        HoleScores: {
          1: 3,
          2: 2,
          3: 3,
          4: 4,
          5: 3,
          6: 3,
          7: 3,
          8: 3,
          9: 3,
          10: 3,
          11: 3,
          12: 3,
          13: 2,
          14: 3,
          15: 2,
          16: 5,
          17: 3,
          18: 4,
        },
        Layout: {
          CourseName: "Bad Rock Creek Disc Golf Course",
          ShortCourseName: "Bad Rock Creek",
          Name: "MPO @ BRC",
          ShortName: "MPO @ BRC",
          Holes: 18,
          Par: 68,
          Length: 10092,
          Units: "Feet",
          Detail: {
            1: {
              Label: "1",
              Length: 575,
              Par: 4,
            },
            10: {
              Label: "10",
              Length: 487,
              Par: 3,
            },
            11: {
              Label: "11",
              Length: 383,
              Par: 3,
            },
            12: {
              Label: "12",
              Length: 652,
              Par: 5,
            },
            13: {
              Label: "13",
              Length: 364,
              Par: 3,
            },
            14: {
              Label: "14",
              Length: 711,
              Par: 4,
            },
            15: {
              Label: "15",
              Length: 288,
              Par: 3,
            },
            16: {
              Label: "16",
              Length: 956,
              Par: 5,
            },
            17: {
              Label: "17",
              Length: 461,
              Par: 4,
            },
            18: {
              Label: "18",
              Length: 924,
              Par: 5,
            },
            2: {
              Label: "2",
              Length: 204,
              Par: 3,
            },
            3: {
              Label: "3",
              Length: 605,
              Par: 4,
            },
            4: {
              Label: "4",
              Length: 835,
              Par: 4,
            },
            5: {
              Label: "5",
              Length: 624,
              Par: 4,
            },
            6: {
              Label: "6",
              Length: 588,
              Par: 4,
            },
            7: {
              Label: "7",
              Length: 411,
              Par: 3,
            },
            8: {
              Label: "8",
              Length: 756,
              Par: 4,
            },
            9: {
              Label: "9",
              Length: 268,
              Par: 3,
            },
          },
        },
      },
    ],
    AverageRoundRating: 1081,
    RatingDiff: 54,
    ToParString: -13,
    Teammates: [],
  },
  hash: "f2d80fd05aaeb0590b9ac10480c3386b",
};
