export default {
  data: {
    DivisionStandings: [
      {
        round: 2,
        division: "MPO",
        scores: [
          {
            ResultID: 210008830,
            FirstName: "Joseph",
            LastName: "Anderson",
            Name: "Joseph Anderson",
            ShortName: "J. Anderson",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1648431-1606604275.jpg",
            FullLocation: "Athens, GA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: -13,
            ParThruRound: -13,
            Tied: false,
            Rounds: "55,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 1,
            Completed: 0,
            RoundScore: 0,
          },
          {
            ResultID: 210008739,
            FirstName: "Sullivan",
            LastName: "Tipton",
            Name: "Sullivan Tipton",
            ShortName: "S. Tipton",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-282786-1649798520.jpg",
            FullLocation: "Indian Springs, AL",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: -9,
            ParThruRound: -9,
            Tied: true,
            Rounds: "59,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 0,
            RoundScore: 0,
          },
          {
            ResultID: 210008770,
            FirstName: "Robert",
            LastName: "Burridge",
            Name: "Robert Burridge",
            ShortName: "R. Burridge",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-391621-1673367020.jpg",
            FullLocation: "Houston, TX",
            Country: "US",
            Nationality: "US",
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: -9,
            ParThruRound: -9,
            Tied: true,
            Rounds: "59,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 0,
            RoundScore: 0,
          },
          {
            ResultID: 210008760,
            FirstName: "Gannon",
            LastName: "Buhr",
            Name: "Gannon Buhr",
            ShortName: "G. Buhr",
            AvatarURL: "/files/styles/large/public/pictures/Gannon-Buhr.jpg",
            FullLocation: "Urbandale, IA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: -8,
            ParThruRound: -8,
            Tied: true,
            Rounds: "60,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 4,
            Completed: 0,
            RoundScore: 0,
          },
        ],
        players: 108,
        shotgun_time: "",
        tee_times: true,
        registered: 108,
      },
      {
        round: 2,
        division: "FPO",
        scores: [
          {
            ResultID: 210008774,
            FirstName: "Ali",
            LastName: "Smith",
            Name: "Ali Smith",
            ShortName: "A. Smith",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1586681-1668105468.jpg",
            FullLocation: "Kansas City, MO",
            Country: "US",
            Nationality: "US",
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: -3,
            ParThruRound: -3,
            Tied: false,
            Rounds: "63,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 1,
            Completed: 0,
            RoundScore: 0,
          },
          {
            ResultID: 210008775,
            FirstName: "Hanna",
            LastName: "Huynh",
            Name: "Hanna Huynh",
            ShortName: "H. Huynh",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1057441-1671159091.jpg",
            FullLocation: "Spokane, WA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: -1,
            ParThruRound: -1,
            Tied: false,
            Rounds: "65,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 0,
            RoundScore: 0,
          },
          {
            ResultID: 210008807,
            FirstName: "Casey",
            LastName: "Pennington",
            Name: "Casey Pennington",
            ShortName: "C. Pennington",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-240716-1614653293.jpg",
            FullLocation: "Kansas City, MO",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: 0,
            ParThruRound: 0,
            Tied: false,
            Rounds: "66,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 3,
            Completed: 0,
            RoundScore: 0,
          },
          {
            ResultID: 210237286,
            FirstName: "Lisa",
            LastName: "Fajkus",
            Name: "Lisa Fajkus",
            ShortName: "L. Fajkus",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-192306-1683062360.jpg",
            FullLocation: "Canyon Lake, TX",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: null,
            RoundtoPar: 0,
            ToPar: 1,
            ParThruRound: 1,
            Tied: true,
            Rounds: "67,,,,,,,,,,,",
            Teammates: [],
            Scores: ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
            RunningPlace: 4,
            Completed: 0,
            RoundScore: 0,
          },
        ],
        players: 26,
        shotgun_time: "",
        tee_times: true,
        registered: 26,
      },
    ],
    HasInternationalPresence: true,
  },
  hash: "84ebb0620b07f68123213f3008ac056b",
};
