export default {
  data: {
    TournID: 66098,
    ResultID: 210008774,
    FirstName: "Ali",
    LastName: "Smith",
    PDGANum: 147050,
    Division: "FPO",
    Pool: "",
    Place: 1,
    PlaceRank: 1,
    ToPar: -3,
    Tied: false,
    Prize: "",
    DNF: false,
    Total: 63,
    Name: "Ali Smith",
    Avatar:
      "/files/styles/large/public/pictures/picture-1586681-1668105468.jpg",
    ProfileURL: "https://www.pdga.com/player/147050",
    DivisionName: "Women's Pro Open",
    FormattedPlace: "1st",
    TierLetter: "A",
    TierType: "Tier",
    Class: "Professional",
    Rating: 940,
    RatingEffectiveDate: "2023-06-13",
    Location: "Kansas City, MO",
    Country: "US",
    Nationality: "US",
    Privacy: "no",
    AvatarURL:
      "/files/styles/large/public/pictures/picture-1586681-1668105468.jpg",
    Scores: [
      {
        Round: 1,
        RoundLabel: "Round 1",
        RoundLabelShort: "Rd 1",
        RoundDate: "2023-07-09",
        RoundField: "Rd1",
        TeeTime: "09:05:00",
        TeeStart: "1",
        RoundScore: 63,
        ScoreToPar: -3,
        RoundToPar: -3,
        Birdies: 5,
        BirdieHoles: 5,
        Bogeys: 2,
        BogeyHoles: 2,
        HotRound: false,
        RoundComplete: true,
        RoundRating: 982,
        HoleScores: {
          1: 4,
          2: 2,
          3: 3,
          4: 3,
          5: 4,
          6: 4,
          7: 3,
          8: 3,
          9: 3,
          10: 3,
          11: 3,
          12: 5,
          13: 4,
          14: 4,
          15: 3,
          16: 4,
          17: 4,
          18: 4,
        },
        Layout: {
          CourseName: "Bad Rock Creek Disc Golf Course",
          ShortCourseName: "Bad Rock Creek",
          Name: "FPO @ BRC",
          ShortName: "FPO @ BRC",
          Holes: 18,
          Par: 66,
          Length: 7927,
          Units: "Feet",
          Detail: {
            1: {
              Label: "1",
              Length: 575,
              Par: 4,
            },
            10: {
              Label: "10",
              Length: 336,
              Par: 3,
            },
            11: {
              Label: "11",
              Length: 286,
              Par: 3,
            },
            12: {
              Label: "12",
              Length: 543,
              Par: 4,
            },
            13: {
              Label: "13",
              Length: 364,
              Par: 3,
            },
            14: {
              Label: "14",
              Length: 582,
              Par: 4,
            },
            15: {
              Label: "15",
              Length: 288,
              Par: 3,
            },
            16: {
              Label: "16",
              Length: 456,
              Par: 4,
            },
            17: {
              Label: "17",
              Length: 461,
              Par: 4,
            },
            18: {
              Label: "18",
              Length: 749,
              Par: 5,
            },
            2: {
              Label: "2",
              Length: 204,
              Par: 3,
            },
            3: {
              Label: "3",
              Length: 474,
              Par: 4,
            },
            4: {
              Label: "4",
              Length: 562,
              Par: 4,
            },
            5: {
              Label: "5",
              Length: 594,
              Par: 4,
            },
            6: {
              Label: "6",
              Length: 471,
              Par: 4,
            },
            7: {
              Label: "7",
              Length: 411,
              Par: 4,
            },
            8: {
              Label: "8",
              Length: 303,
              Par: 3,
            },
            9: {
              Label: "9",
              Length: 268,
              Par: 3,
            },
          },
        },
      },
    ],
    AverageRoundRating: 982,
    RatingDiff: 42,
    ToParString: -3,
    Teammates: [],
  },
  hash: "0bb0c31a7e442519e1cfc21931552649",
};
