export default {
  data: {
    Tournaments: [
      {
        TournID: 69181,
        StartDate: "2023-07-11",
        EndDate: "2023-07-15",
        Name: "2023 PDGA Amateur Masters Disc Golf World Championships",
        Tier: "Major",
        AdministrativeAreaISO: "AZ",
        CountryISO: "US",
        Players: 499,
        EventDate: "Jul 11",
        SimpleName: "2023 PDGA Amateur Masters Disc Golf World Championships",
        HighestTier: "M",
        ShortLocation: "AZ",
        Location: "Flagstaff, AZ",
        RawTier: "M",
        FormattedTier: "Major",
        FormattedLongTier: "Major",
        DateRange: "Tue-Sat, Jul 11-15, 2023",
      },
      {
        TournID: 66511,
        StartDate: "2023-07-11",
        EndDate: "2023-07-15",
        Name: "2023 PDGA Professional Masters Disc Golf World Championships",
        Tier: "Major",
        AdministrativeAreaISO: "AZ",
        CountryISO: "US",
        Players: 393,
        EventDate: "Jul 11",
        SimpleName:
          "2023 PDGA Professional Masters Disc Golf World Championships",
        HighestTier: "M",
        ShortLocation: "AZ",
        Location: "Flagstaff, AZ",
        RawTier: "M",
        FormattedTier: "Major",
        FormattedLongTier: "Major",
        DateRange: "Tue-Sat, Jul 11-15, 2023",
      },
      {
        TournID: 71412,
        StartDate: "2023-07-11",
        EndDate: "2023-07-11",
        Name: "OMG\u00c5NG 12 - Uppsala FDKs tisdagsgolf - Pro tees presented by CLEAN DRINK",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 1,
        EventDate: "Jul 11",
        SimpleName: "OMG\u00c5NG 12 - Uppsala FDKs tisdagsgolf - Pro tees",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "Uppsala, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Tuesday, Jul 11",
      },
      {
        TournID: 72492,
        StartDate: "2023-07-10",
        EndDate: "2023-07-10",
        Name: "Dynamic Discs Flex at County Park Green",
        Tier: "C",
        AdministrativeAreaISO: "WI",
        CountryISO: "US",
        Players: 4,
        EventDate: "Jul 10",
        SimpleName: "Dynamic Discs Flex at County Park Green",
        HighestTier: "C",
        ShortLocation: "WI",
        Location: "Oshkosh, WI",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Monday, Jul 10",
      },
      {
        TournID: 72518,
        StartDate: "2023-07-10",
        EndDate: "2023-07-10",
        Name: "Rock Ridge Flex IV",
        Tier: "C",
        AdministrativeAreaISO: "NC",
        CountryISO: "US",
        Players: 7,
        EventDate: "Jul 10",
        SimpleName: "Rock Ridge Flex IV",
        HighestTier: "C",
        ShortLocation: "NC",
        Location: "Moncure, NC",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Monday, Jul 10",
      },
      {
        TournID: 70324,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "2023 Daytona Open Presented by Dynamic Discs and Discgolfcenter.com",
        Tier: "B",
        AdministrativeAreaISO: "FL",
        CountryISO: "US",
        Players: 95,
        EventDate: "Jul 08",
        SimpleName: "2023 Daytona Open",
        HighestTier: "B",
        ShortLocation: "FL",
        Location: "Daytona Beach, FL",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 65074,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "2023 High Country Throwdown driven by Innova",
        Tier: "C",
        AdministrativeAreaISO: "NC",
        CountryISO: "US",
        Players: 64,
        EventDate: "Jul 08",
        SimpleName: "2023 High Country Throwdown",
        HighestTier: "C",
        ShortLocation: "NC",
        Location: "Jefferson, NC",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 70353,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "2023 Iron Thrown Series Event #4",
        Tier: "C",
        AdministrativeAreaISO: "AL",
        CountryISO: "US",
        Players: 59,
        EventDate: "Jul 08",
        SimpleName: "2023 Iron Thrown Series Event #4",
        HighestTier: "C",
        ShortLocation: "AL",
        Location: "Trussville, AL",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 69120,
        StartDate: "2023-07-07",
        EndDate: "2023-07-09",
        Name: "2023 Rose City Open Presented by Huk Lab",
        Tier: "B",
        AdministrativeAreaISO: "OR",
        CountryISO: "US",
        Players: 132,
        EventDate: "Jul 07",
        SimpleName: "2023 Rose City Open",
        HighestTier: "B",
        ShortLocation: "OR",
        Location: "Portland, OR",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Fri-Sun, Jul 7-9, 2023",
      },
      {
        TournID: 65005,
        StartDate: "2023-07-07",
        EndDate: "2023-07-09",
        Name: "20th Annual Live Oak Summer Open",
        Tier: "A",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 251,
        EventDate: "Jul 07",
        SimpleName: "20th Annual Live Oak Summer Open",
        HighestTier: "A",
        ShortLocation: "TX",
        Location: "Live Oak, TX",
        RawTier: "A",
        FormattedTier: "A-Tier",
        FormattedLongTier: "A-Tier",
        DateRange: "Fri-Sun, Jul 7-9, 2023",
      },
      {
        TournID: 67942,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "3rd Annual Ace Chase Palooza",
        Tier: "B",
        AdministrativeAreaISO: "NC",
        CountryISO: "US",
        Players: 105,
        EventDate: "Jul 09",
        SimpleName: "3rd Annual Ace Chase Palooza",
        HighestTier: "B",
        ShortLocation: "NC",
        Location: "Raleigh, NC",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 69866,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "4. Offene Discgolf Hessenmeisterschaft",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "DE",
        Players: 66,
        EventDate: "Jul 08",
        SimpleName: "4. Offene Discgolf Hessenmeisterschaft",
        HighestTier: "C",
        ShortLocation: "DE",
        Location: "Calden, Germany",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 71001,
        StartDate: "2023-07-07",
        EndDate: "2023-07-09",
        Name: "Baltic Disc Golf Championships 2023 presented by Innova Champion Discs",
        Tier: "B",
        AdministrativeAreaISO: "67",
        CountryISO: "EE",
        Players: 93,
        EventDate: "Jul 07",
        SimpleName: "Baltic Disc Golf Championships 2023",
        HighestTier: "B",
        ShortLocation: "EE",
        Location: "P\u00e4rnu, 67, Estonia",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Fri-Sun, Jul 7-9, 2023",
      },
      {
        TournID: 70269,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Battle at Memorial 6",
        Tier: "C",
        AdministrativeAreaISO: "IN",
        CountryISO: "US",
        Players: 85,
        EventDate: "Jul 09",
        SimpleName: "Battle at Memorial 6",
        HighestTier: "B",
        ShortLocation: "IN",
        Location: "Huntington , IN",
        RawTier: "C/B",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C/B-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 71871,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Branford Bash Fund Raiser",
        Tier: "C",
        AdministrativeAreaISO: "",
        CountryISO: "NZ",
        Players: 38,
        EventDate: "Jul 09",
        SimpleName: "Branford Bash Fund Raiser",
        HighestTier: "C",
        ShortLocation: "NZ",
        Location: "Nelson, New Zealand",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 70125,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Brewport Open - All Other Am",
        Tier: "B",
        AdministrativeAreaISO: "CT",
        CountryISO: "US",
        Players: 72,
        EventDate: "Jul 09",
        SimpleName: "Brewport Open - All Other Am",
        HighestTier: "B",
        ShortLocation: "CT",
        Location: "Bridgeport, CT",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 65890,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "Cass Clay Summer Slam IV sponsored by Rock 30 Games",
        Tier: "B",
        AdministrativeAreaISO: "ND",
        CountryISO: "US",
        Players: 119,
        EventDate: "Jul 08",
        SimpleName: "Cass Clay Summer Slam IV",
        HighestTier: "B",
        ShortLocation: "ND",
        Location: "Fargo, ND",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 71711,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Charlie Vettiner Open Flex 2",
        Tier: "C",
        AdministrativeAreaISO: "KY",
        CountryISO: "US",
        Players: 57,
        EventDate: "Jul 09",
        SimpleName: "Charlie Vettiner Open Flex 2",
        HighestTier: "C",
        ShortLocation: "KY",
        Location: "La Grange, KY",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 66044,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "Clash at The Canyons VII",
        Tier: "B",
        AdministrativeAreaISO: "IL",
        CountryISO: "US",
        Players: 274,
        EventDate: "Jul 08",
        SimpleName: "Clash at The Canyons VII",
        HighestTier: "B",
        ShortLocation: "IL",
        Location: "Lockport, IL",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 64851,
        StartDate: "2023-07-07",
        EndDate: "2023-07-09",
        Name: "DGMT - The Camden Open Presented By Innova",
        Tier: "B",
        AdministrativeAreaISO: "IL",
        CountryISO: "US",
        Players: 88,
        EventDate: "Jul 07",
        SimpleName: "DGMT - The Camden Open",
        HighestTier: "B",
        ShortLocation: "IL",
        Location: "Milan, IL",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Fri-Sun, Jul 7-9, 2023",
      },
      {
        TournID: 66098,
        StartDate: "2023-07-07",
        EndDate: "2023-07-09",
        Name: "DGPT Silver - GRIPeq 41st Kansas City Wide Open Sponsored by Dynamic Discs",
        Tier: "A",
        AdministrativeAreaISO: "MO",
        CountryISO: "US",
        Players: 134,
        EventDate: "Jul 07",
        SimpleName: "DGPT Silver - GRIPeq 41st Kansas City Wide Open",
        HighestTier: "A",
        ShortLocation: "MO",
        Location: "Liberty, MO",
        RawTier: "A",
        FormattedTier: "A-Tier",
        FormattedLongTier: "A-Tier",
        DateRange: "Fri-Sun, Jul 7-9, 2023",
      },
      {
        TournID: 67713,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "DGVTour #6 - Jeezum Crow Jam",
        Tier: "C",
        AdministrativeAreaISO: "VT",
        CountryISO: "US",
        Players: 73,
        EventDate: "Jul 08",
        SimpleName: "DGVTour #6 - Jeezum Crow Jam",
        HighestTier: "C",
        ShortLocation: "VT",
        Location: "Jay, VT",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 66339,
        StartDate: "2023-07-07",
        EndDate: "2023-07-09",
        Name: "Disc Connection Queensland Open 2023",
        Tier: "B",
        AdministrativeAreaISO: "QLD",
        CountryISO: "AU",
        Players: 163,
        EventDate: "Jul 07",
        SimpleName: "Disc Connection Queensland Open 2023",
        HighestTier: "B",
        ShortLocation: "AU",
        Location: "Strathpine, QLD, Australia",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Fri-Sun, Jul 7-9, 2023",
      },
      {
        TournID: 70435,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Disc Revolution Presents the Aviary Flex 2",
        Tier: "C",
        AdministrativeAreaISO: "CO",
        CountryISO: "US",
        Players: 75,
        EventDate: "Jul 09",
        SimpleName: "the Aviary Flex 2",
        HighestTier: "C",
        ShortLocation: "CO",
        Location: "Colorado Springs, CO",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 72566,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Discorti la flor de Enka",
        Tier: "C",
        AdministrativeAreaISO: "ANT",
        CountryISO: "CO",
        Players: 28,
        EventDate: "Jul 09",
        SimpleName: "Discorti la flor de Enka",
        HighestTier: "C",
        ShortLocation: "CO",
        Location: "Girardota, ANT, Colombia",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 66652,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Double Down Dubs Run Scrapyard ",
        Tier: "C",
        AdministrativeAreaISO: "NC",
        CountryISO: "US",
        Players: 86,
        EventDate: "Jul 09",
        SimpleName: "Double Down Dubs Run Scrapyard",
        HighestTier: "C",
        ShortLocation: "NC",
        Location: "Matthews, NC",
        RawTier: "XC",
        FormattedTier: "C-Tier",
        FormattedLongTier: "XC-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 72505,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "Droga Golfowa Challenge ",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "PL",
        Players: 72,
        EventDate: "Jul 08",
        SimpleName: "Droga Golfowa Challenge",
        HighestTier: "C",
        ShortLocation: "PL",
        Location: "Warsaw, Poland",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 70882,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: 'E.R.I.C. vs Cancer Presents "Too Hot To Handle" Engineered by Dynamic Discs Carrollton - PRO & INT',
        Tier: "B",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 52,
        EventDate: "Jul 09",
        SimpleName:
          '"Too Hot To Handle" Engineered by Dynamic Discs Carrollton - PRO & INT',
        HighestTier: "B",
        ShortLocation: "TX",
        Location: "The Colony, TX",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 71295,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Earth Driven by Innova",
        Tier: "B",
        AdministrativeAreaISO: "NJ",
        CountryISO: "US",
        Players: 72,
        EventDate: "Jul 09",
        SimpleName: "Earth",
        HighestTier: "B",
        ShortLocation: "NJ",
        Location: "Mahwah, NJ",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 71526,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "Eighth Annual Buffalo Flying Disc Open",
        Tier: "B",
        AdministrativeAreaISO: "NY",
        CountryISO: "US",
        Players: 125,
        EventDate: "Jul 08",
        SimpleName: "Eighth Annual Buffalo Flying Disc Open",
        HighestTier: "B",
        ShortLocation: "NY",
        Location: "Ransomville, NY",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 64029,
        StartDate: "2023-07-07",
        EndDate: "2023-07-09",
        Name: "ET#5 - Skellefte\u00e5 Open presented by Latitude 64\u00b0",
        Tier: "A",
        AdministrativeAreaISO: "",
        CountryISO: "SE",
        Players: 144,
        EventDate: "Jul 07",
        SimpleName: "ET#5 - Skellefte\u00e5 Open",
        HighestTier: "A",
        ShortLocation: "SE",
        Location: "Skelleftea, Sweden",
        RawTier: "A",
        FormattedTier: "A-Tier",
        FormattedLongTier: "A-Tier",
        DateRange: "Fri-Sun, Jul 7-9, 2023",
      },
      {
        TournID: 70666,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Farm Path Tour presents Clash at Haikey",
        Tier: "C",
        AdministrativeAreaISO: "OK",
        CountryISO: "US",
        Players: 55,
        EventDate: "Jul 09",
        SimpleName: "Clash at Haikey",
        HighestTier: "C",
        ShortLocation: "OK",
        Location: "Broken Arrow, OK",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 69233,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "Fly Exclusive presents The 3rd annual Kinston Open : Driven by Innova",
        Tier: "B",
        AdministrativeAreaISO: "NC",
        CountryISO: "US",
        Players: 132,
        EventDate: "Jul 08",
        SimpleName: "The 3rd annual Kinston Open",
        HighestTier: "B",
        ShortLocation: "NC",
        Location: "Kinston, NC",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 70886,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Grandview Rendezvous 2023",
        Tier: "C",
        AdministrativeAreaISO: "IA",
        CountryISO: "US",
        Players: 90,
        EventDate: "Jul 09",
        SimpleName: "Grandview Rendezvous 2023",
        HighestTier: "C",
        ShortLocation: "IA",
        Location: "Des Moines, IA",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 70218,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "Hammond Farm Pop Up",
        Tier: "C",
        AdministrativeAreaISO: "ME",
        CountryISO: "US",
        Players: 49,
        EventDate: "Jul 09",
        SimpleName: "Hammond Farm Pop Up",
        HighestTier: "C",
        ShortLocation: "ME",
        Location: "North Berwick, ME",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 67301,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "Hub City Huck 2023",
        Tier: "B",
        AdministrativeAreaISO: "BC",
        CountryISO: "CA",
        Players: 72,
        EventDate: "Jul 08",
        SimpleName: "Hub City Huck 2023",
        HighestTier: "B",
        ShortLocation: "BC",
        Location: "Nanaimo, BC",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 70899,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "Huck Face BrOpen III Throwkyo Drift",
        Tier: "C",
        AdministrativeAreaISO: "CO",
        CountryISO: "US",
        Players: 83,
        EventDate: "Jul 08",
        SimpleName: "Huck Face BrOpen III Throwkyo Drift",
        HighestTier: "C",
        ShortLocation: "CO",
        Location: "Greeley, CO",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 69568,
        StartDate: "2023-07-08",
        EndDate: "2023-07-09",
        Name: "III OVIEDO OPEN - presented by Innova",
        Tier: "C",
        AdministrativeAreaISO: "O",
        CountryISO: "ES",
        Players: 70,
        EventDate: "Jul 08",
        SimpleName: "III OVIEDO OPEN",
        HighestTier: "C",
        ShortLocation: "ES",
        Location: "Oviedo, O, Spain",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sat-Sun, Jul 8-9, 2023",
      },
      {
        TournID: 71372,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "IronSchu '23",
        Tier: "B",
        AdministrativeAreaISO: "MD",
        CountryISO: "US",
        Players: 57,
        EventDate: "Jul 09",
        SimpleName: "IronSchu '23",
        HighestTier: "B",
        ShortLocation: "MD",
        Location: "Salisbury, MD",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 70360,
        StartDate: "2023-07-09",
        EndDate: "2023-07-09",
        Name: "It\u00e4-Suomi Masters 2023",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "FI",
        Players: 72,
        EventDate: "Jul 09",
        SimpleName: "It\u00e4-Suomi Masters 2023",
        HighestTier: "C",
        ShortLocation: "FI",
        Location: "Pieks\u00e4m\u00e4ki, Finland",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Sunday, Jul 9",
      },
      {
        TournID: 69630,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Professional Divisional Doubles at 2023 PDGA Masters Worlds",
        Tier: "C",
        AdministrativeAreaISO: "AZ",
        CountryISO: "US",
        Players: 66,
        EventDate: "Jul 08",
        SimpleName:
          "Professional Divisional Doubles at 2023 PDGA Masters Worlds",
        HighestTier: "C",
        ShortLocation: "AZ",
        Location: "Flagstaff, AZ",
        RawTier: "XC",
        FormattedTier: "C-Tier",
        FormattedLongTier: "XC-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 69033,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Rare Air Discs presents The Olympic City Open",
        Tier: "C",
        AdministrativeAreaISO: "CO",
        CountryISO: "US",
        Players: 68,
        EventDate: "Jul 08",
        SimpleName: "The Olympic City Open",
        HighestTier: "C",
        ShortLocation: "CO",
        Location: "Widefield, CO",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 69413,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "RevolutionRace Tour #12 - Ymer",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 139,
        EventDate: "Jul 08",
        SimpleName: "RevolutionRace Tour #12 - Ymer",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "Bor\u00e5s, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 68006,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Ridge Runner",
        Tier: "C",
        AdministrativeAreaISO: "MO",
        CountryISO: "US",
        Players: 92,
        EventDate: "Jul 08",
        SimpleName: "Ridge Runner",
        HighestTier: "C",
        ShortLocation: "MO",
        Location: "Wentzville, MO",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 71828,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "River Dogs Open",
        Tier: "C",
        AdministrativeAreaISO: "AB",
        CountryISO: "CA",
        Players: 71,
        EventDate: "Jul 08",
        SimpleName: "River Dogs Open",
        HighestTier: "C",
        ShortLocation: "AB",
        Location: "Calgary, AB",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 71454,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Sagebrush GIGOGR",
        Tier: "C",
        AdministrativeAreaISO: "BC",
        CountryISO: "CA",
        Players: 36,
        EventDate: "Jul 08",
        SimpleName: "Sagebrush GIGOGR",
        HighestTier: "C",
        ShortLocation: "BC",
        Location: "Kamloops, BC",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70622,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Sand Creek Open",
        Tier: "C",
        AdministrativeAreaISO: "KS",
        CountryISO: "US",
        Players: 51,
        EventDate: "Jul 08",
        SimpleName: "Sand Creek Open",
        HighestTier: "C",
        ShortLocation: "KS",
        Location: "Newton, KS",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70482,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "SJVDGC Summer Melee presented by Ecig-Works",
        Tier: "C",
        AdministrativeAreaISO: "IN",
        CountryISO: "US",
        Players: 82,
        EventDate: "Jul 08",
        SimpleName: "SJVDGC Summer Melee",
        HighestTier: "C",
        ShortLocation: "IN",
        Location: "South Bend, IN",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 72211,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Skellefte\u00e5 Open Week - Wasteland",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 39,
        EventDate: "Jul 08",
        SimpleName: "Skellefte\u00e5 Open Week - Wasteland",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "Robertsfors, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 67130,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "SoCo Championship Qualifier: 2nd Annual SoCo Patriot Games",
        Tier: "C",
        AdministrativeAreaISO: "CO",
        CountryISO: "US",
        Players: 22,
        EventDate: "Jul 08",
        SimpleName:
          "SoCo Championship Qualifier: 2nd Annual SoCo Patriot Games",
        HighestTier: "C",
        ShortLocation: "CO",
        Location: "Alamosa , CO",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70321,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "S\u00f6dra Norrlandstouren 2023 presented by Westside discs ",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 90,
        EventDate: "Jul 08",
        SimpleName: "S\u00f6dra Norrlandstouren 2023",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "S\u00f6derhamn, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70068,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Summer Showdown ",
        Tier: "C",
        AdministrativeAreaISO: "BC",
        CountryISO: "CA",
        Players: 35,
        EventDate: "Jul 08",
        SimpleName: "Summer Showdown",
        HighestTier: "C",
        ShortLocation: "BC",
        Location: "Mission, BC",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 64954,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The 3rd Annual Central Classic Presented by 1010 Discs",
        Tier: "C",
        AdministrativeAreaISO: "MS",
        CountryISO: "US",
        Players: 72,
        EventDate: "Jul 08",
        SimpleName: "The 3rd Annual Central Classic",
        HighestTier: "C",
        ShortLocation: "MS",
        Location: "Southaven, MS",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70287,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The 3rd Annual Triple Double presented by Lebanon Valley Disc Golf",
        Tier: "C",
        AdministrativeAreaISO: "PA",
        CountryISO: "US",
        Players: 166,
        EventDate: "Jul 08",
        SimpleName: "The 3rd Annual Triple Double",
        HighestTier: "C",
        ShortLocation: "PA",
        Location: "Myerstown, PA",
        RawTier: "XC",
        FormattedTier: "C-Tier",
        FormattedLongTier: "XC-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 69674,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The Dairytown Throwdown",
        Tier: "C",
        AdministrativeAreaISO: "NB",
        CountryISO: "CA",
        Players: 47,
        EventDate: "Jul 08",
        SimpleName: "The Dairytown Throwdown",
        HighestTier: "C",
        ShortLocation: "NB",
        Location: "Sussex, NB",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 69858,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The Michiana Pro Shop Presents The Swinney Showdown",
        Tier: "C",
        AdministrativeAreaISO: "IN",
        CountryISO: "US",
        Players: 101,
        EventDate: "Jul 08",
        SimpleName: "The Swinney Showdown",
        HighestTier: "C",
        ShortLocation: "IN",
        Location: "Fort Wayne, IN",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70686,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The Midland Open - MP40, FP40, MA1, MA40, FA40, MA3",
        Tier: "B",
        AdministrativeAreaISO: "MI",
        CountryISO: "US",
        Players: 40,
        EventDate: "Jul 08",
        SimpleName: "The Midland Open - MP40, FP40, MA1, MA40, FA40, MA3",
        HighestTier: "B",
        ShortLocation: "MI",
        Location: "Midland, MI",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 71846,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The NYDGA Junior Series - Mid-Season Mayhem Presented by Schmult Dental Services and Gateway",
        Tier: "C",
        AdministrativeAreaISO: "OK",
        CountryISO: "US",
        Players: 25,
        EventDate: "Jul 08",
        SimpleName: "The NYDGA Junior Series - Mid-Season Mayhem",
        HighestTier: "C",
        ShortLocation: "OK",
        Location: "Norman, OK",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 71679,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The Sunflower Open 2 Driven by Innova ",
        Tier: "C",
        AdministrativeAreaISO: "NC",
        CountryISO: "US",
        Players: 67,
        EventDate: "Jul 08",
        SimpleName: "The Sunflower Open 2",
        HighestTier: "C",
        ShortLocation: "NC",
        Location: "Whiteville , NC",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 72303,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The Table Setter",
        Tier: "C",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 20,
        EventDate: "Jul 08",
        SimpleName: "The Table Setter",
        HighestTier: "C",
        ShortLocation: "TX",
        Location: "The Woodlands, TX",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70779,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "The Winona Open",
        Tier: "C",
        AdministrativeAreaISO: "MN",
        CountryISO: "US",
        Players: 38,
        EventDate: "Jul 08",
        SimpleName: "The Winona Open",
        HighestTier: "C",
        ShortLocation: "MN",
        Location: "Winona, MN",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 71838,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Tournament For A Legend - Rocket City",
        Tier: "C",
        AdministrativeAreaISO: "AL",
        CountryISO: "US",
        Players: 158,
        EventDate: "Jul 08",
        SimpleName: "Tournament For A Legend - Rocket City",
        HighestTier: "C",
        ShortLocation: "AL",
        Location: "Huntsville, AL",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70702,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Tri-Fox Flex #2",
        Tier: "C",
        AdministrativeAreaISO: "WI",
        CountryISO: "US",
        Players: 82,
        EventDate: "Jul 08",
        SimpleName: "Tri-Fox Flex #2",
        HighestTier: "C",
        ShortLocation: "WI",
        Location: "Burlington , WI",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 64831,
        StartDate: "2023-07-06",
        EndDate: "2023-07-08",
        Name: "Tyyni X - 10th time anniversary event",
        Tier: "A",
        AdministrativeAreaISO: "",
        CountryISO: "FI",
        Players: 539,
        EventDate: "Jul 06",
        SimpleName: "Tyyni X - 10th time anniversary event",
        HighestTier: "A",
        ShortLocation: "FI",
        Location: "Sipoo, Kerava, Tuusula, Finland",
        RawTier: "A",
        FormattedTier: "A-Tier",
        FormattedLongTier: "A-Tier",
        DateRange: "Jul 6-8, 2023",
      },
      {
        TournID: 71758,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "Ultuna - Powered by J\u00e4rva DGP",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 25,
        EventDate: "Jul 08",
        SimpleName: "Ultuna",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "Uppsala, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 72316,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "V\u00e4stg\u00f6tatouren 4 - Habo",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 88,
        EventDate: "Jul 08",
        SimpleName: "V\u00e4stg\u00f6tatouren 4 - Habo",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "Habo, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 66371,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "West Michigan Open",
        Tier: "C",
        AdministrativeAreaISO: "MI",
        CountryISO: "US",
        Players: 73,
        EventDate: "Jul 08",
        SimpleName: "West Michigan Open",
        HighestTier: "C",
        ShortLocation: "MI",
        Location: "Sparta, MI",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 70534,
        StartDate: "2023-07-08",
        EndDate: "2023-07-08",
        Name: "White Spruce Open - Saturday",
        Tier: "B",
        AdministrativeAreaISO: "ON",
        CountryISO: "CA",
        Players: 126,
        EventDate: "Jul 08",
        SimpleName: "White Spruce Open - Saturday",
        HighestTier: "B",
        ShortLocation: "ON",
        Location: "Brampton, ON",
        RawTier: "B",
        FormattedTier: "B-Tier",
        FormattedLongTier: "B-Tier",
        DateRange: "Saturday, Jul 8, 2023",
      },
      {
        TournID: 71614,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Circle 1 Flex Series @ Woodland Valley #4",
        Tier: "C",
        AdministrativeAreaISO: "ME",
        CountryISO: "US",
        Players: 57,
        EventDate: "Jul 07",
        SimpleName: "Circle 1 Flex Series @ Woodland Valley #4",
        HighestTier: "C",
        ShortLocation: "ME",
        Location: "Limerick, ME",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 70717,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Cosmic Monthly - Maple Hill (4/8) - Cosmic Glory",
        Tier: "C",
        AdministrativeAreaISO: "MA",
        CountryISO: "US",
        Players: 96,
        EventDate: "Jul 07",
        SimpleName: "Cosmic Monthly - Maple Hill (4/8) - Cosmic Glory",
        HighestTier: "C",
        ShortLocation: "MA",
        Location: "Leicester, MA",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 70719,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Cosmic Monthly - Stafford Woods (4/8) - Sole",
        Tier: "C",
        AdministrativeAreaISO: "NJ",
        CountryISO: "US",
        Players: 42,
        EventDate: "Jul 07",
        SimpleName: "Cosmic Monthly - Stafford Woods (4/8) - Sole",
        HighestTier: "C",
        ShortLocation: "NJ",
        Location: "Voorhees Township, NJ",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 70718,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Cosmic Monthly - Tower Ridge (4/8) - Whites",
        Tier: "C",
        AdministrativeAreaISO: "CT",
        CountryISO: "US",
        Players: 13,
        EventDate: "Jul 07",
        SimpleName: "Cosmic Monthly - Tower Ridge (4/8) - Whites",
        HighestTier: "C",
        ShortLocation: "CT",
        Location: "Simsbury, CT",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72300,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Dynamic Discs Flex Start Friday @ Bill Allen Presented by E.R.I.C. vs Cancer",
        Tier: "C",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 103,
        EventDate: "Jul 07",
        SimpleName: "Dynamic Discs Flex Start Friday @ Bill Allen",
        HighestTier: "C",
        ShortLocation: "TX",
        Location: "The Colony, TX",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72553,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Dynamic Discs NWA Flex Start Friday #10 at NorthArk College",
        Tier: "C",
        AdministrativeAreaISO: "AR",
        CountryISO: "US",
        Players: 21,
        EventDate: "Jul 07",
        SimpleName:
          "Dynamic Discs NWA Flex Start Friday #10 at NorthArk College",
        HighestTier: "C",
        ShortLocation: "AR",
        Location: "Harrison, AR",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72407,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Every Fourth FLEX",
        Tier: "C",
        AdministrativeAreaISO: "IL",
        CountryISO: "US",
        Players: 65,
        EventDate: "Jul 07",
        SimpleName: "Every Fourth FLEX",
        HighestTier: "C",
        ShortLocation: "IL",
        Location: "Oswego, IL",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 70825,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Friday Flex @ Bethel 2",
        Tier: "C",
        AdministrativeAreaISO: "MN",
        CountryISO: "US",
        Players: 86,
        EventDate: "Jul 07",
        SimpleName: "Friday Flex @ Bethel 2",
        HighestTier: "C",
        ShortLocation: "MN",
        Location: "Arden Hills, MN",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72523,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Griplocked Flex Friday @ Audubon 7/7",
        Tier: "C",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 23,
        EventDate: "Jul 07",
        SimpleName: "Griplocked Flex Friday @ Audubon 7/7",
        HighestTier: "C",
        ShortLocation: "TX",
        Location: "Garland, TX",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72525,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Oggwood Freedom Flex",
        Tier: "C",
        AdministrativeAreaISO: "TN",
        CountryISO: "US",
        Players: 21,
        EventDate: "Jul 07",
        SimpleName: "Oggwood Freedom Flex",
        HighestTier: "C",
        ShortLocation: "TN",
        Location: "Cedar Hill, TN",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72033,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Pre-Battle Skirmish 2023",
        Tier: "C",
        AdministrativeAreaISO: "IN",
        CountryISO: "US",
        Players: 51,
        EventDate: "Jul 07",
        SimpleName: "Pre-Battle Skirmish 2023",
        HighestTier: "C",
        ShortLocation: "IN",
        Location: "Huntington , IN",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72498,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Red Tailed Ridge Flex-Start",
        Tier: "C",
        AdministrativeAreaISO: "AB",
        CountryISO: "CA",
        Players: 14,
        EventDate: "Jul 07",
        SimpleName: "Red Tailed Ridge Flex-Start",
        HighestTier: "C",
        ShortLocation: "AB",
        Location: "Rockyview County, AB",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 71452,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Sagebrush Women's GIGOGR",
        Tier: "C",
        AdministrativeAreaISO: "BC",
        CountryISO: "CA",
        Players: 7,
        EventDate: "Jul 07",
        SimpleName: "Sagebrush Women's GIGOGR",
        HighestTier: "C",
        ShortLocation: "BC",
        Location: "Kamloops, BC",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 71560,
        StartDate: "2023-07-07",
        EndDate: "2023-07-07",
        Name: "Sunset at Sanders Ferry Glow Disc Golf Tournament Presented by Discin' Disciples (CEP Charity - Rated)",
        Tier: "C",
        AdministrativeAreaISO: "TN",
        CountryISO: "US",
        Players: 35,
        EventDate: "Jul 07",
        SimpleName: "Sunset at Sanders Ferry Glow Disc Golf Tournament",
        HighestTier: "C",
        ShortLocation: "TN",
        Location: "Hendersonville, TN",
        RawTier: "XC",
        FormattedTier: "C-Tier",
        FormattedLongTier: "XC-Tier",
        DateRange: "Friday, Jul 7, 2023",
      },
      {
        TournID: 72092,
        StartDate: "2023-07-06",
        EndDate: "2023-07-06",
        Name: "Crossover Thursday Night Flights Summer Series #4 2023",
        Tier: "C",
        AdministrativeAreaISO: "OH",
        CountryISO: "US",
        Players: 52,
        EventDate: "Jul 06",
        SimpleName: "Crossover Thursday Night Flights Summer Series #4 2023",
        HighestTier: "C",
        ShortLocation: "OH",
        Location: "Cincinnati, OH",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Thursday, Jul 6, 2023",
      },
      {
        TournID: 71754,
        StartDate: "2023-07-06",
        EndDate: "2023-07-06",
        Name: "Lone Star Disc Thursday Flex @ StoneBridge 7/6",
        Tier: "C",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 63,
        EventDate: "Jul 06",
        SimpleName: "Lone Star Disc Thursday Flex @ StoneBridge 7/6",
        HighestTier: "C",
        ShortLocation: "TX",
        Location: "The Woodlands, TX",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Thursday, Jul 6, 2023",
      },
      {
        TournID: 72463,
        StartDate: "2023-07-06",
        EndDate: "2023-07-06",
        Name: "LOSO Warm up Hillside ",
        Tier: "C",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 45,
        EventDate: "Jul 06",
        SimpleName: "LOSO Warm up Hillside",
        HighestTier: "C",
        ShortLocation: "TX",
        Location: "Live Oak, TX",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Thursday, Jul 6, 2023",
      },
      {
        TournID: 72519,
        StartDate: "2023-07-06",
        EndDate: "2023-07-06",
        Name: "\u00d6rebrotouren 2023 #10 Brickeberg Bakre",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 80,
        EventDate: "Jul 06",
        SimpleName: "\u00d6rebrotouren 2023 #10 Brickeberg Bakre",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "\u00d6rebro, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Thursday, Jul 6, 2023",
      },
      {
        TournID: 72209,
        StartDate: "2023-07-06",
        EndDate: "2023-07-06",
        Name: "Skellefte\u00e5 Open Week - Skogsparken",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 14,
        EventDate: "Jul 06",
        SimpleName: "Skellefte\u00e5 Open Week - Skogsparken",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "Lycksele, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Thursday, Jul 6, 2023",
      },
      {
        TournID: 72502,
        StartDate: "2023-07-06",
        EndDate: "2023-07-06",
        Name: "Wallachian proDiscgolf tour - #5 Europe Burov",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "CZ",
        Players: 32,
        EventDate: "Jul 06",
        SimpleName: "Wallachian proDiscgolf tour - #5 Europe Burov",
        HighestTier: "C",
        ShortLocation: "CZ",
        Location: "Vala\u0161sk\u00e1 Byst\u0159ice, Czech Republic",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Thursday, Jul 6, 2023",
      },
      {
        TournID: 72273,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "1 Round 1 Rating @ Burt",
        Tier: "C",
        AdministrativeAreaISO: "MI",
        CountryISO: "US",
        Players: 33,
        EventDate: "Jul 05",
        SimpleName: "1 Round 1 Rating @ Burt",
        HighestTier: "C",
        ShortLocation: "MI",
        Location: "Burt, MI",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
      {
        TournID: 71858,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "Ale Disc Golf Center - Stegen # 11",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 23,
        EventDate: "Jul 05",
        SimpleName: "Ale Disc Golf Center - Stegen # 11",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "N\u00f6dinge-Nol, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
      {
        TournID: 72351,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "Big Country Beef Jerky flex #10",
        Tier: "C",
        AdministrativeAreaISO: "TX",
        CountryISO: "US",
        Players: 25,
        EventDate: "Jul 05",
        SimpleName: "Big Country Beef Jerky flex #10",
        HighestTier: "C",
        ShortLocation: "TX",
        Location: "Temple , TX",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
      {
        TournID: 72501,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "Mistrovstv\u00ed Vala\u0161sk\u00e9ho Kr\u00e1lovstv\u00ed 2023",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "CZ",
        Players: 19,
        EventDate: "Jul 05",
        SimpleName:
          "Mistrovstv\u00ed Vala\u0161sk\u00e9ho Kr\u00e1lovstv\u00ed 2023",
        HighestTier: "C",
        ShortLocation: "CZ",
        Location: "Vala\u0161sk\u00e1 Byst\u0159ice, Czech Republic",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
      {
        TournID: 72441,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "Onsdags Touren #4",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "SE",
        Players: 50,
        EventDate: "Jul 05",
        SimpleName: "Onsdags Touren #4",
        HighestTier: "C",
        ShortLocation: "SE",
        Location: "Lund, Sweden",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
      {
        TournID: 70028,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "Tyyni After Dawn Nevas #2",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "FI",
        Players: 41,
        EventDate: "Jul 05",
        SimpleName: "Tyyni After Dawn Nevas #2",
        HighestTier: "C",
        ShortLocation: "FI",
        Location: "Sipoo, Finland",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
      {
        TournID: 70026,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "Tyyni One Round Fuzzy Eagle Kartano",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "FI",
        Players: 256,
        EventDate: "Jul 05",
        SimpleName: "Tyyni One Round Fuzzy Eagle Kartano",
        HighestTier: "C",
        ShortLocation: "FI",
        Location: "Sipoo, Finland",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
      {
        TournID: 70025,
        StartDate: "2023-07-05",
        EndDate: "2023-07-05",
        Name: "Tyyni One Round Sibbe",
        Tier: "C",
        AdministrativeAreaISO: null,
        CountryISO: "FI",
        Players: 266,
        EventDate: "Jul 05",
        SimpleName: "Tyyni One Round Sibbe",
        HighestTier: "C",
        ShortLocation: "FI",
        Location: "Sipoo, Finland",
        RawTier: "C",
        FormattedTier: "C-Tier",
        FormattedLongTier: "C-Tier",
        DateRange: "Wednesday, Jul 5, 2023",
      },
    ],
    Leagues: [
      {
        TournID: 71741,
        StartDate: "2023-06-13",
        EndDate: "2023-08-01",
        Name: "- 12th Annual Huron Valley Sanctioned Singles ",
        Tier: "L",
        Players: 72,
        EventDate: "Jun-Aug",
        CountryISO: "US",
        AdministrativeAreaISO: "MI",
        SimpleName: "- 12th Annual Huron Valley Sanctioned Singles",
        HighestTier: "L",
        ShortLocation: "MI",
        Location: "Milford, MI",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Tuesdays \u00b7 Jun 13 - Aug 1",
      },
      {
        TournID: 72310,
        StartDate: "2023-06-28",
        EndDate: "2023-08-02",
        Name: "- 1st  Annual Hump Day Summer Singles",
        Tier: "L",
        Players: 19,
        EventDate: "Jun-Aug",
        CountryISO: "US",
        AdministrativeAreaISO: "MI",
        SimpleName: "- 1st  Annual Hump Day Summer Singles",
        HighestTier: "L",
        ShortLocation: "MI",
        Location: "Ypsilanti, MI",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Wednesdays \u00b7 Jun 28 - Aug 2",
      },
      {
        TournID: 71683,
        StartDate: "2023-06-05",
        EndDate: "2023-07-10",
        Name: "-Lakeside Loot League- Season 3 Presented by Ark Genetics  // $100 Weekly Cash Added//CTPs//Ace Pool",
        Tier: "L",
        Players: 61,
        EventDate: "Jun-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "AZ",
        SimpleName: "-Lakeside Loot League- Season 3",
        HighestTier: "L",
        ShortLocation: "AZ",
        Location: "Tucson, AZ",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Mondays \u00b7 Jun 5 - Jul 10",
      },
      {
        TournID: 71499,
        StartDate: "2023-06-07",
        EndDate: "2023-08-09",
        Name: "2023 Ace Coalition Summer League",
        Tier: "L",
        Players: 49,
        EventDate: "Jun-Aug",
        CountryISO: "US",
        AdministrativeAreaISO: "SD",
        SimpleName: "2023 Ace Coalition Summer League",
        HighestTier: "L",
        ShortLocation: "SD",
        Location: "Yankton, SD",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Wednesdays \u00b7 Jun 7 - Aug 9",
      },
      {
        TournID: 70532,
        StartDate: "2023-06-29",
        EndDate: "2023-08-24",
        Name: "2023 Akron PDGA Fall",
        Tier: "L",
        Players: 56,
        EventDate: "Jun-Aug",
        CountryISO: "US",
        AdministrativeAreaISO: "PA",
        SimpleName: "2023 Akron PDGA Fall",
        HighestTier: "L",
        ShortLocation: "PA",
        Location: "Akron, PA",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Thursdays \u00b7 Jun 29 - Aug 24",
      },
      {
        TournID: 72101,
        StartDate: "2023-07-03",
        EndDate: "2023-09-04",
        Name: "2023 Beer City Disc Golf Summer Sanctioned League - Grand Rapids Rotary North",
        Tier: "L",
        Players: 18,
        EventDate: "Jul-Sep",
        CountryISO: "US",
        AdministrativeAreaISO: "MI",
        SimpleName:
          "2023 Beer City Disc Golf Summer Sanctioned League - Grand Rapids Rotary North",
        HighestTier: "L",
        ShortLocation: "MI",
        Location: "Belmont, MI",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Mondays \u00b7 Jul 3 - Sep 4",
      },
      {
        TournID: 69787,
        StartDate: "2023-05-30",
        EndDate: "2023-08-01",
        Name: "2023 Birch Point Disc Golf League",
        Tier: "L",
        Players: 45,
        EventDate: "May-Aug",
        CountryISO: "CA",
        AdministrativeAreaISO: "ON",
        SimpleName: "2023 Birch Point Disc Golf League",
        HighestTier: "L",
        ShortLocation: "ON",
        Location: "Thunder Bay, ON",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Tuesdays \u00b7 May 30 - Aug 1",
      },
      {
        TournID: 70860,
        StartDate: "2023-06-07",
        EndDate: "2023-07-12",
        Name: "2023 CADL Wednesday League_Pt. 2",
        Tier: "L",
        Players: 47,
        EventDate: "Jun-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "NC",
        SimpleName: "2023 CADL Wednesday League_Pt. 2",
        HighestTier: "L",
        ShortLocation: "NC",
        Location: "Raleigh, NC",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Wednesdays \u00b7 Jun 7 - Jul 12",
      },
      {
        TournID: 71998,
        StartDate: "2023-06-16",
        EndDate: "2023-08-04",
        Name: "2023 Crossroads DGC Summer Junior League",
        Tier: "L",
        Players: 9,
        EventDate: "Jun-Aug",
        CountryISO: "US",
        AdministrativeAreaISO: "IN",
        SimpleName: "2023 Crossroads DGC Summer Junior League",
        HighestTier: "L",
        ShortLocation: "IN",
        Location: "Terre Haute , IN",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Fridays \u00b7 Jun 16 - Aug 4",
      },
      {
        TournID: 71231,
        StartDate: "2023-05-22",
        EndDate: "2023-07-24",
        Name: "2023 Deer Lakes League - Session 2",
        Tier: "L",
        Players: 68,
        EventDate: "May-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "PA",
        SimpleName: "2023 Deer Lakes League - Session 2",
        HighestTier: "L",
        ShortLocation: "PA",
        Location: "Tarentum, PA",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Mondays \u00b7 May 22 - Jul 24",
      },
      {
        TournID: 72447,
        StartDate: "2023-07-07",
        EndDate: "2023-09-08",
        Name: "2023 GASDG Sanctioned Singles #2 - MA3-4/FA1-4",
        Tier: "L",
        Players: 17,
        EventDate: "Jul-Sep",
        CountryISO: "US",
        AdministrativeAreaISO: "OH",
        SimpleName: "2023 GASDG Sanctioned Singles #2 - MA3-4/FA1-4",
        HighestTier: "L",
        ShortLocation: "OH",
        Location: "Grand Rapids, OH",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Fridays \u00b7 Jul 7 - Sep 8",
      },
      {
        TournID: 72576,
        StartDate: "2023-07-07",
        EndDate: "2023-09-08",
        Name: "2023 GASDG Sanctioned Singles #2 - MPO/FPO, MA1-2",
        Tier: "L",
        Players: 10,
        EventDate: "Jul-Sep",
        CountryISO: "US",
        AdministrativeAreaISO: "OH",
        SimpleName: "2023 GASDG Sanctioned Singles #2 - MPO/FPO, MA1-2",
        HighestTier: "L",
        ShortLocation: "OH",
        Location: "Grand Rapids, OH",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Fridays \u00b7 Jul 7 - Sep 8",
      },
      {
        TournID: 71271,
        StartDate: "2023-05-31",
        EndDate: "2023-07-12",
        Name: "2023 GASDG Southern Summer Singles - MA3-4/FA1-4",
        Tier: "L",
        Players: 14,
        EventDate: "May-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "OH",
        SimpleName: "2023 GASDG Southern Summer Singles - MA3-4/FA1-4",
        HighestTier: "L",
        ShortLocation: "OH",
        Location: "Van Buren, OH",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Wednesdays \u00b7 May 31 - Jul 12",
      },
      {
        TournID: 71272,
        StartDate: "2023-05-31",
        EndDate: "2023-07-12",
        Name: "2023 GASDG Southern Summer Singles - MPO/FPO, MA1-2",
        Tier: "L",
        Players: 13,
        EventDate: "May-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "OH",
        SimpleName: "2023 GASDG Southern Summer Singles - MPO/FPO, MA1-2",
        HighestTier: "L",
        ShortLocation: "OH",
        Location: "Van Buren, OH",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Wednesdays \u00b7 May 31 - Jul 12",
      },
      {
        TournID: 71327,
        StartDate: "2023-06-13",
        EndDate: "2023-08-15",
        Name: "2023 Grove City PDGA League - Session 2",
        Tier: "L",
        Players: 56,
        EventDate: "Jun-Aug",
        CountryISO: "US",
        AdministrativeAreaISO: "PA",
        SimpleName: "2023 Grove City PDGA League - Session 2",
        HighestTier: "L",
        ShortLocation: "PA",
        Location: "Grove City, PA",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Tuesdays \u00b7 Jun 13 - Aug 15",
      },
      {
        TournID: 71073,
        StartDate: "2023-06-12",
        EndDate: "2023-08-07",
        Name: "2023 Hub City Disc Golf Club Summer League",
        Tier: "L",
        Players: 59,
        EventDate: "Jun-Aug",
        CountryISO: "US",
        AdministrativeAreaISO: "SC",
        SimpleName: "2023 Hub City Disc Golf Club Summer League",
        HighestTier: "L",
        ShortLocation: "SC",
        Location: "Woodruff, SC",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Mondays \u00b7 Jun 12 - Aug 7",
      },
      {
        TournID: 69743,
        StartDate: "2023-05-10",
        EndDate: "2023-07-12",
        Name: "2023 Hump Days at Herr",
        Tier: "L",
        Players: 59,
        EventDate: "May-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "PA",
        SimpleName: "2023 Hump Days at Herr",
        HighestTier: "L",
        ShortLocation: "PA",
        Location: "Lancaster, PA",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Wednesdays \u00b7 May 10 - Jul 12",
      },
      {
        TournID: 71012,
        StartDate: "2023-05-21",
        EndDate: "2023-07-23",
        Name: "2023 IDGC Hot Weather and Hotter Scores (hopefully) ",
        Tier: "L",
        Players: 95,
        EventDate: "May-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "GA",
        SimpleName: "2023 IDGC Hot Weather and Hotter Scores (hopefully)",
        HighestTier: "L",
        ShortLocation: "GA",
        Location: "Appling , GA",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Sundays \u00b7 May 21 - Jul 23",
      },
      {
        TournID: 71068,
        StartDate: "2023-05-16",
        EndDate: "2023-07-18",
        Name: "2023 JPP sanctioned league Session 2 presented by BRIA Disc Golf",
        Tier: "L",
        Players: 7,
        EventDate: "May-Jul",
        CountryISO: "US",
        AdministrativeAreaISO: "NJ",
        SimpleName: "2023 JPP sanctioned league Session 2",
        HighestTier: "L",
        ShortLocation: "NJ",
        Location: "Ocean, NJ",
        RawTier: "L",
        FormattedTier: "League",
        FormattedLongTier: "League",
        DateRange: "Tuesdays \u00b7 May 16 - Jul 18",
      },
    ],
  },
  hash: "867cf7033f037ec625c7e0c877f46d39",
};
