export default {
  data: {
    DivisionStandings: [
      {
        round: 2,
        division: "MPO",
        scores: [
          {
            ResultID: 210008760,
            FirstName: "Gannon",
            LastName: "Buhr",
            Name: "Gannon Buhr",
            ShortName: "G. Buhr",
            AvatarURL: "/files/styles/large/public/pictures/Gannon-Buhr.jpg",
            FullLocation: "Urbandale, IA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:25:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -12,
            ToPar: -40,
            ParThruRound: -20,
            Tied: false,
            Rounds: "60,56,60,,,,,,,,,",
            Teammates: [],
            Scores: "3,2,4,4,4,3,2,4,2,3,2,4,2,3,3,4,3,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 1,
            Completed: 1,
            RoundScore: 56,
          },
          {
            ResultID: 210008830,
            FirstName: "Joseph",
            LastName: "Anderson",
            Name: "Joseph Anderson",
            ShortName: "J. Anderson",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1648431-1606604275.jpg",
            FullLocation: "Athens, GA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:25:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -5,
            ToPar: -31,
            ParThruRound: -18,
            Tied: false,
            Rounds: "55,63,60,,,,,,,,,",
            Teammates: [],
            Scores: "4,2,5,4,3,3,3,5,3,3,2,3,4,4,4,4,3,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 1,
            RoundScore: 63,
          },
          {
            ResultID: 210008792,
            FirstName: "Jake",
            LastName: "Hebenheimer",
            Name: "Jake Hebenheimer",
            ShortName: "J. Hebenheimer",
            AvatarURL: null,
            FullLocation: "Jefferson Cty, MO",
            Country: "US",
            Nationality: "US",
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "14:37:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -12,
            ToPar: -37,
            ParThruRound: -17,
            Tied: false,
            Rounds: "63,56,60,,,,,,,,,",
            Teammates: [],
            Scores: "3,2,3,4,4,4,2,3,2,4,3,4,2,3,2,4,3,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 3,
            Completed: 1,
            RoundScore: 56,
          },
          {
            ResultID: 210008789,
            FirstName: "Evan",
            LastName: "Scott",
            Name: "Evan Scott",
            ShortName: "E. Scott",
            AvatarURL: null,
            FullLocation: "Duncan, SC",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:05:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -9,
            ToPar: -25,
            ParThruRound: -16,
            Tied: false,
            Rounds: "61,59,68,,,,,,,,,",
            Teammates: [],
            Scores: "4,2,3,3,4,3,2,4,2,3,3,4,2,3,4,5,4,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 4,
            Completed: 1,
            RoundScore: 59,
          },
        ],
        players: 108,
        shotgun_time: "",
        tee_times: true,
        registered: 108,
      },
      {
        round: 2,
        division: "FPO",
        scores: [
          {
            ResultID: 210008774,
            FirstName: "Ali",
            LastName: "Smith",
            Name: "Ali Smith",
            ShortName: "A. Smith",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1586681-1668105468.jpg",
            FullLocation: "Kansas City, MO",
            Country: "US",
            Nationality: "US",
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: 1,
            ToPar: 0,
            ParThruRound: -2,
            Tied: false,
            Rounds: "63,67,67,,,,,,,,,",
            Teammates: [],
            Scores: "4,6,4,3,5,4,3,3,3,2,3,5,4,3,3,4,4,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 1,
            Completed: 1,
            RoundScore: 67,
          },
          {
            ResultID: 210008775,
            FirstName: "Hanna",
            LastName: "Huynh",
            Name: "Hanna Huynh",
            ShortName: "H. Huynh",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1057441-1671159091.jpg",
            FullLocation: "Spokane, WA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: 1,
            ToPar: 2,
            ParThruRound: 0,
            Tied: false,
            Rounds: "65,67,67,,,,,,,,,",
            Teammates: [],
            Scores: "6,3,3,4,4,4,3,3,3,2,2,4,3,6,5,3,4,5,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 1,
            RoundScore: 67,
          },
          {
            ResultID: 210237286,
            FirstName: "Lisa",
            LastName: "Fajkus",
            Name: "Lisa Fajkus",
            ShortName: "L. Fajkus",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-192306-1683062360.jpg",
            FullLocation: "Canyon Lake, TX",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: 0,
            ToPar: 4,
            ParThruRound: 1,
            Tied: false,
            Rounds: "67,66,69,,,,,,,,,",
            Teammates: [],
            Scores: "3,2,3,5,5,4,3,4,3,4,3,3,3,4,5,3,4,5,,,,,,,,,,,,,,,,,,",
            RunningPlace: 3,
            Completed: 1,
            RoundScore: 66,
          },
          {
            ResultID: 210008776,
            FirstName: "Holyn",
            LastName: "Handley",
            Name: "Holyn Handley",
            ShortName: "H. Handley",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1397416-1678127130.jpg",
            FullLocation: "Grapevine, TX",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:05:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: 4,
            ToPar: 5,
            ParThruRound: 5,
            Tied: false,
            Rounds: "67,70,62,,,,,,,,,",
            Teammates: [],
            Scores: "4,2,4,4,4,4,5,4,3,4,2,6,4,4,3,4,4,5,,,,,,,,,,,,,,,,,,",
            RunningPlace: 4,
            Completed: 1,
            RoundScore: 70,
          },
        ],
        players: 26,
        shotgun_time: "",
        tee_times: true,
        registered: 26,
      },
    ],
    HasInternationalPresence: true,
  },
  hash: "5dcc928dcea5127f9444922e3f618d59",
};
