export default {
  data: {
    DivisionStandings: [
      {
        round: 1,
        division: "MPO",
        scores: [
          {
            ResultID: 210008830,
            FirstName: "Joseph",
            LastName: "Anderson",
            Name: "Joseph Anderson",
            ShortName: "J. Anderson",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1648431-1606604275.jpg",
            FullLocation: "Athens, GA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "13:20:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -13,
            ToPar: -39,
            ParThruRound: -13,
            Tied: false,
            Rounds: "55,63,60,,,,,,,,,",
            Teammates: [],
            Scores: "3,2,3,4,3,3,3,3,3,3,3,3,2,3,2,5,3,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 1,
            Completed: 1,
            RoundScore: 55,
          },
          {
            ResultID: 210008739,
            FirstName: "Sullivan",
            LastName: "Tipton",
            Name: "Sullivan Tipton",
            ShortName: "S. Tipton",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-282786-1649798520.jpg",
            FullLocation: "Indian Springs, AL",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "11:19:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -9,
            ToPar: -32,
            ParThruRound: -9,
            Tied: true,
            Rounds: "59,64,58,,,,,,,,,",
            Teammates: [],
            Scores: "4,3,3,4,3,3,3,3,3,2,4,4,2,4,3,4,3,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 1,
            RoundScore: 59,
          },
          {
            ResultID: 210008770,
            FirstName: "Robert",
            LastName: "Burridge",
            Name: "Robert Burridge",
            ShortName: "R. Burridge",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-391621-1673367020.jpg",
            FullLocation: "Houston, TX",
            Country: "US",
            Nationality: "US",
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "10:57:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -9,
            ToPar: -28,
            ParThruRound: -9,
            Tied: true,
            Rounds: "59,62,64,,,,,,,,,",
            Teammates: [],
            Scores: "3,2,3,3,3,4,2,4,3,2,2,4,3,4,3,5,3,6,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 1,
            RoundScore: 59,
          },
          {
            ResultID: 210008760,
            FirstName: "Gannon",
            LastName: "Buhr",
            Name: "Gannon Buhr",
            ShortName: "G. Buhr",
            AvatarURL: "/files/styles/large/public/pictures/Gannon-Buhr.jpg",
            FullLocation: "Urbandale, IA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "15:25:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -8,
            ToPar: -36,
            ParThruRound: -8,
            Tied: true,
            Rounds: "60,56,60,,,,,,,,,",
            Teammates: [],
            Scores: "3,3,5,3,3,4,3,4,2,4,4,4,2,3,2,4,3,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 4,
            Completed: 1,
            RoundScore: 60,
          },
        ],
        players: 108,
        shotgun_time: "",
        tee_times: true,
        registered: 108,
      },
      {
        round: 1,
        division: "FPO",
        scores: [
          {
            ResultID: 210008774,
            FirstName: "Ali",
            LastName: "Smith",
            Name: "Ali Smith",
            ShortName: "A. Smith",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1586681-1668105468.jpg",
            FullLocation: "Kansas City, MO",
            Country: "US",
            Nationality: "US",
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:05:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -3,
            ToPar: -4,
            ParThruRound: -3,
            Tied: false,
            Rounds: "63,67,67,,,,,,,,,",
            Teammates: [],
            Scores: "4,2,3,3,4,4,3,3,3,3,3,5,4,4,3,4,4,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 1,
            Completed: 1,
            RoundScore: 63,
          },
          {
            ResultID: 210008775,
            FirstName: "Hanna",
            LastName: "Huynh",
            Name: "Hanna Huynh",
            ShortName: "H. Huynh",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-1057441-1671159091.jpg",
            FullLocation: "Spokane, WA",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "08:36:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: -1,
            ToPar: 0,
            ParThruRound: -1,
            Tied: false,
            Rounds: "65,67,67,,,,,,,,,",
            Teammates: [],
            Scores: "5,5,3,4,4,4,4,2,3,2,3,5,3,3,4,3,4,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 2,
            Completed: 1,
            RoundScore: 65,
          },
          {
            ResultID: 210008807,
            FirstName: "Casey",
            LastName: "Pennington",
            Name: "Casey Pennington",
            ShortName: "C. Pennington",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-240716-1614653293.jpg",
            FullLocation: "Kansas City, MO",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:25:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: 0,
            ToPar: 7,
            ParThruRound: 0,
            Tied: false,
            Rounds: "66,74,65,,,,,,,,,",
            Teammates: [],
            Scores: "5,4,4,3,4,3,5,3,4,3,2,4,3,4,2,5,4,4,,,,,,,,,,,,,,,,,,",
            RunningPlace: 3,
            Completed: 1,
            RoundScore: 66,
          },
          {
            ResultID: 210237286,
            FirstName: "Lisa",
            LastName: "Fajkus",
            Name: "Lisa Fajkus",
            ShortName: "L. Fajkus",
            AvatarURL:
              "/files/styles/large/public/pictures/picture-192306-1683062360.jpg",
            FullLocation: "Canyon Lake, TX",
            Country: "US",
            Nationality: null,
            Team: null,
            TeamName: null,
            Prize: null,
            TeeTime: "09:05:00",
            TeeStart: "",
            Played: 18,
            RoundtoPar: 1,
            ToPar: 5,
            ParThruRound: 1,
            Tied: true,
            Rounds: "67,66,69,,,,,,,,,",
            Teammates: [],
            Scores: "6,4,3,5,4,4,4,2,4,2,3,3,3,4,3,4,4,5,,,,,,,,,,,,,,,,,,",
            RunningPlace: 4,
            Completed: 1,
            RoundScore: 67,
          },
        ],
        players: 26,
        shotgun_time: "",
        tee_times: true,
        registered: 26,
      },
    ],
    HasInternationalPresence: true,
  },
  hash: "96c3912470878e98727f053474278db3",
};
