export default [
  {
    data: {
      DateRange: "Fri-Sun, Jul 7-9, 2023",
      EndDate: "2023-07-09",
      Country: "United States",
      Location: "Liberty, Missouri",
      LocationShort: "Liberty, MO",
      Divisions: [
        {
          DivisionID: 100,
          Division: "MPO",
          DivisionName: "Mixed Pro Open",
          Players: 108,
          LayoutAssignments: {
            1: 623210,
            2: 623210,
            3: 623210,
          },
          IsPro: true,
          ShortName: "Mixed Pro Open",
          AbbreviatedName: "Mixed Pro Open",
          LatestRound: "2",
        },
        {
          DivisionID: 105,
          Division: "FPO",
          DivisionName: "Women's Pro Open",
          Players: 26,
          LayoutAssignments: {
            1: 623211,
            2: 623211,
            3: 623211,
          },
          IsPro: true,
          ShortName: "Women's Pro Open",
          AbbreviatedName: "Women's Pro Open",
          LatestRound: "2",
        },
      ],
      Finals: "no",
      HighestCompletedRound: 1,
      LatestRound: "2",
      FinalRound: 3,
      Layouts: [
        {
          LayoutID: 623210,
          CourseID: 211226,
          CourseName: "Bad Rock Creek",
          Name: "MPO @ BRC",
          Holes: 18,
          Par: 68,
          Length: 10092,
          Units: "Feet",
          Accuracy: "M",
          Details: [
            {
              Hole: "H1",
              Label: "1",
              Par: 4,
              Length: 575,
            },
            {
              Hole: "H2",
              Label: "2",
              Par: 3,
              Length: 204,
            },
            {
              Hole: "H3",
              Label: "3",
              Par: 4,
              Length: 605,
            },
            {
              Hole: "H4",
              Label: "4",
              Par: 4,
              Length: 835,
            },
            {
              Hole: "H5",
              Label: "5",
              Par: 4,
              Length: 624,
            },
            {
              Hole: "H6",
              Label: "6",
              Par: 4,
              Length: 588,
            },
            {
              Hole: "H7",
              Label: "7",
              Par: 3,
              Length: 411,
            },
            {
              Hole: "H8",
              Label: "8",
              Par: 4,
              Length: 756,
            },
            {
              Hole: "H9",
              Label: "9",
              Par: 3,
              Length: 268,
            },
            {
              Hole: "H10",
              Label: "10",
              Par: 3,
              Length: 487,
            },
            {
              Hole: "H11",
              Label: "11",
              Par: 3,
              Length: 383,
            },
            {
              Hole: "H12",
              Label: "12",
              Par: 5,
              Length: 652,
            },
            {
              Hole: "H13",
              Label: "13",
              Par: 3,
              Length: 364,
            },
            {
              Hole: "H14",
              Label: "14",
              Par: 4,
              Length: 711,
            },
            {
              Hole: "H15",
              Label: "15",
              Par: 3,
              Length: 288,
            },
            {
              Hole: "H16",
              Label: "16",
              Par: 5,
              Length: 956,
            },
            {
              Hole: "H17",
              Label: "17",
              Par: 4,
              Length: 461,
            },
            {
              Hole: "H18",
              Label: "18",
              Par: 5,
              Length: 924,
            },
          ],
        },
        {
          LayoutID: 623211,
          CourseID: 211226,
          CourseName: "Bad Rock Creek",
          Name: "FPO @ BRC",
          Holes: 18,
          Par: 66,
          Length: 7927,
          Units: "Feet",
          Accuracy: "M",
          Details: [
            {
              Hole: "H1",
              Label: "1",
              Par: 4,
              Length: 575,
            },
            {
              Hole: "H2",
              Label: "2",
              Par: 3,
              Length: 204,
            },
            {
              Hole: "H3",
              Label: "3",
              Par: 4,
              Length: 474,
            },
            {
              Hole: "H4",
              Label: "4",
              Par: 4,
              Length: 562,
            },
            {
              Hole: "H5",
              Label: "5",
              Par: 4,
              Length: 594,
            },
            {
              Hole: "H6",
              Label: "6",
              Par: 4,
              Length: 471,
            },
            {
              Hole: "H7",
              Label: "7",
              Par: 4,
              Length: 411,
            },
            {
              Hole: "H8",
              Label: "8",
              Par: 3,
              Length: 303,
            },
            {
              Hole: "H9",
              Label: "9",
              Par: 3,
              Length: 268,
            },
            {
              Hole: "H10",
              Label: "10",
              Par: 3,
              Length: 336,
            },
            {
              Hole: "H11",
              Label: "11",
              Par: 3,
              Length: 286,
            },
            {
              Hole: "H12",
              Label: "12",
              Par: 4,
              Length: 543,
            },
            {
              Hole: "H13",
              Label: "13",
              Par: 3,
              Length: 364,
            },
            {
              Hole: "H14",
              Label: "14",
              Par: 4,
              Length: 582,
            },
            {
              Hole: "H15",
              Label: "15",
              Par: 3,
              Length: 288,
            },
            {
              Hole: "H16",
              Label: "16",
              Par: 4,
              Length: 456,
            },
            {
              Hole: "H17",
              Label: "17",
              Par: 4,
              Length: 461,
            },
            {
              Hole: "H18",
              Label: "18",
              Par: 5,
              Length: 749,
            },
          ],
        },
      ],
      LayoutIDs: [
        {
          Division: "FPO",
          Pool: "",
          1: 623211,
          2: 623211,
          3: 623211,
          4: 623210,
          5: 623210,
          6: 623210,
          7: 623210,
          8: 623210,
          9: 623210,
          10: 623210,
          11: 623210,
          12: 623210,
        },
        {
          Division: "MPO",
          Pool: "",
          1: 623210,
          2: 623210,
          3: 623210,
          4: 623210,
          5: 623210,
          6: 623210,
          7: 623210,
          8: 623210,
          9: 623210,
          10: 623210,
          11: 623210,
          12: 623210,
        },
      ],
      Name: "DGPT Silver - GRIPeq 41st Kansas City Wide Open Sponsored by Dynamic Discs",
      NameHtml:
        "DGPT Silver - GRIPeq 41st Kansas City Wide Open Sponsored by Dynamic Discs",
      MultiLineName: {
        pre: "",
        main: "DGPT Silver - GRIPeq 41st Kansas City Wide Open",
        post: "Sponsored by Dynamic Discs",
      },
      MultiLineNameHtml:
        ' <span class="event-name-main">DGPT Silver - GRIPeq 41st Kansas City Wide Open</span> <span class="event-name-post">Sponsored by Dynamic Discs</span>',
      RawTier: "A",
      Rounds: 3,
      RoundsList: {
        1: {
          Number: 1,
          Label: "Round 1",
          LabelAbbreviated: "Rd 1",
          Date: "2023-07-09",
          DateAbbreviated: "Jul 9",
          ShowDate: false,
        },
        2: {
          Number: 2,
          Label: "Round 2",
          LabelAbbreviated: "Rd 2",
          Date: "2023-07-09",
          DateAbbreviated: "Jul 9",
          ShowDate: false,
        },
        3: {
          Number: 3,
          Label: "Round 3",
          LabelAbbreviated: "Rd 3",
          Date: "2023-07-09",
          DateAbbreviated: "Jul 9",
          ShowDate: false,
        },
      },
      Semis: "no",
      SimpleName: "DGPT Silver - GRIPeq 41st Kansas City Wide Open",
      StartDate: "2023-07-07",
      TDName: "Jerry Patterson",
      TDPDGANum: 73600,
      Tier: "A",
      FormattedTier: "A-Tier",
      FormattedLongTier: "A-Tier",
      TierPro: "A",
      TierAm: "A",
      TierX: false,
      TotalPlayers: 0,
      TournamentId: "66098",
      International: true,
    },
    hash: "871e580ffbdf49b98558556e33bdd70a",
  },
];
